"""Job File PDF export for completed PM projects.

Generates a complete, archivable PDF dossier of a finished project — header
(with the pro's logo if set), summary, Kanban tasks, materials, work diary,
change orders (Nachträge), milestone payments, financials/P&L and an embedded
photo gallery (job progress photos + material photos pulled from GridFS).

Available to both the Pro (own projects) and the Homeowner (their projects),
ONLY when the project status == "done". The caller passes a `lang` code
(en/de/tr/es) which localises every label in the document.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from io import BytesIO
from typing import Any, Optional

from bson import ObjectId

from database import db, fs_bucket
from services.pro_invoicing import get_pro_snapshot, _fmt_eur

logger = logging.getLogger(__name__)

SUPPORTED_LANGS = ("en", "de", "tr", "es")
MAX_PHOTOS = 24  # safety cap so the dossier stays a sane size

# ──────────────────────────────────────────────
# Localised labels
# ──────────────────────────────────────────────
LABELS: dict[str, dict[str, str]] = {
    "en": {
        "doc_title": "Job File", "doc_subtitle": "Completed project dossier",
        "generated_on": "Generated on", "project": "Project", "status": "Status",
        "category": "Category", "customer": "Customer", "tradesperson": "Tradesperson",
        "address": "Address", "created": "Created", "completed": "Completed",
        "sec_summary": "Summary", "sec_tasks": "Tasks (Kanban)",
        "sec_materials": "Materials", "sec_diary": "Work diary",
        "sec_change_orders": "Change orders (Nachträge)", "sec_payments": "Milestone payments",
        "sec_financials": "Financials", "sec_photos": "Photos",
        "col_todo": "To do", "col_doing": "In progress", "col_done": "Done",
        "th_task": "Task", "th_assignee": "Assignee", "th_due": "Due",
        "th_name": "Name", "th_qty": "Qty", "th_planned": "Planned", "th_actual": "Actual",
        "th_supplier": "Supplier", "th_date": "Date", "th_hours": "Hours", "th_note": "Note",
        "th_number": "No.", "th_title": "Title", "th_net": "Net", "th_gross": "Gross",
        "th_label": "Milestone", "th_amount": "Amount", "th_reference": "Reference",
        "fin_revenue": "Revenue (quote)", "fin_extras": "Approved extras",
        "fin_new_total": "New project total", "fin_materials": "Materials (actual)",
        "fin_labour": "Labour", "fin_profit": "Profit (est.)", "fin_margin": "Margin",
        "labour_detail": "{h} h × {r}/h",
        "status_active": "Active", "status_on_hold": "On hold", "status_done": "Completed",
        "status_archived": "Archived",
        "co_sent": "Sent", "co_approved": "Approved", "co_rejected": "Declined", "co_invoiced": "Invoiced",
        "pay_requested": "Requested", "pay_client_marked_paid": "Marked paid", "pay_paid": "Paid",
        "none": "—", "no_items": "No entries.",
        "footer": "Job File — generated by ServiceMarket",
        "total_hours": "Total hours logged",
    },
    "de": {
        "doc_title": "Auftragsakte", "doc_subtitle": "Dossier des abgeschlossenen Projekts",
        "generated_on": "Erstellt am", "project": "Projekt", "status": "Status",
        "category": "Kategorie", "customer": "Kunde", "tradesperson": "Auftragnehmer",
        "address": "Adresse", "created": "Erstellt", "completed": "Abgeschlossen",
        "sec_summary": "Zusammenfassung", "sec_tasks": "Aufgaben (Kanban)",
        "sec_materials": "Material", "sec_diary": "Bautagebuch",
        "sec_change_orders": "Nachträge", "sec_payments": "Zahlungsmeilensteine",
        "sec_financials": "Finanzen", "sec_photos": "Fotos",
        "col_todo": "Zu erledigen", "col_doing": "In Arbeit", "col_done": "Erledigt",
        "th_task": "Aufgabe", "th_assignee": "Zuständig", "th_due": "Fällig",
        "th_name": "Bezeichnung", "th_qty": "Menge", "th_planned": "Geplant", "th_actual": "Tatsächlich",
        "th_supplier": "Lieferant", "th_date": "Datum", "th_hours": "Stunden", "th_note": "Notiz",
        "th_number": "Nr.", "th_title": "Titel", "th_net": "Netto", "th_gross": "Brutto",
        "th_label": "Meilenstein", "th_amount": "Betrag", "th_reference": "Verwendungszweck",
        "fin_revenue": "Umsatz (Angebot)", "fin_extras": "Genehmigte Nachträge",
        "fin_new_total": "Neue Projektsumme", "fin_materials": "Material (tatsächlich)",
        "fin_labour": "Arbeitszeit", "fin_profit": "Gewinn (geschätzt)", "fin_margin": "Marge",
        "labour_detail": "{h} h × {r}/h",
        "status_active": "Aktiv", "status_on_hold": "Pausiert", "status_done": "Abgeschlossen",
        "status_archived": "Archiviert",
        "co_sent": "Gesendet", "co_approved": "Genehmigt", "co_rejected": "Abgelehnt", "co_invoiced": "Berechnet",
        "pay_requested": "Angefordert", "pay_client_marked_paid": "Als bezahlt markiert", "pay_paid": "Bezahlt",
        "none": "—", "no_items": "Keine Einträge.",
        "footer": "Auftragsakte — erstellt von ServiceMarket",
        "total_hours": "Erfasste Stunden gesamt",
    },
    "tr": {
        "doc_title": "İş Dosyası", "doc_subtitle": "Tamamlanan proje dosyası",
        "generated_on": "Oluşturulma", "project": "Proje", "status": "Durum",
        "category": "Kategori", "customer": "Müşteri", "tradesperson": "Usta",
        "address": "Adres", "created": "Oluşturuldu", "completed": "Tamamlandı",
        "sec_summary": "Özet", "sec_tasks": "Görevler (Kanban)",
        "sec_materials": "Malzemeler", "sec_diary": "İş günlüğü",
        "sec_change_orders": "Değişiklik talepleri", "sec_payments": "Ödeme kilometre taşları",
        "sec_financials": "Finans", "sec_photos": "Fotoğraflar",
        "col_todo": "Yapılacak", "col_doing": "Devam ediyor", "col_done": "Bitti",
        "th_task": "Görev", "th_assignee": "Atanan", "th_due": "Bitiş",
        "th_name": "Ad", "th_qty": "Adet", "th_planned": "Planlanan", "th_actual": "Gerçek",
        "th_supplier": "Tedarikçi", "th_date": "Tarih", "th_hours": "Saat", "th_note": "Not",
        "th_number": "No", "th_title": "Başlık", "th_net": "Net", "th_gross": "Brüt",
        "th_label": "Kilometre taşı", "th_amount": "Tutar", "th_reference": "Açıklama",
        "fin_revenue": "Gelir (teklif)", "fin_extras": "Onaylı ek işler",
        "fin_new_total": "Yeni proje toplamı", "fin_materials": "Malzeme (gerçek)",
        "fin_labour": "İşçilik", "fin_profit": "Kâr (tahmini)", "fin_margin": "Marj",
        "labour_detail": "{h} saat × {r}/saat",
        "status_active": "Aktif", "status_on_hold": "Beklemede", "status_done": "Tamamlandı",
        "status_archived": "Arşivlendi",
        "co_sent": "Gönderildi", "co_approved": "Onaylandı", "co_rejected": "Reddedildi", "co_invoiced": "Faturalandı",
        "pay_requested": "Talep edildi", "pay_client_marked_paid": "Ödendi işaretlendi", "pay_paid": "Ödendi",
        "none": "—", "no_items": "Kayıt yok.",
        "footer": "İş Dosyası — ServiceMarket tarafından oluşturuldu",
        "total_hours": "Toplam kaydedilen saat",
    },
    "es": {
        "doc_title": "Expediente del trabajo", "doc_subtitle": "Dosier del proyecto finalizado",
        "generated_on": "Generado el", "project": "Proyecto", "status": "Estado",
        "category": "Categoría", "customer": "Cliente", "tradesperson": "Profesional",
        "address": "Dirección", "created": "Creado", "completed": "Finalizado",
        "sec_summary": "Resumen", "sec_tasks": "Tareas (Kanban)",
        "sec_materials": "Materiales", "sec_diary": "Diario de obra",
        "sec_change_orders": "Órdenes de cambio", "sec_payments": "Hitos de pago",
        "sec_financials": "Finanzas", "sec_photos": "Fotos",
        "col_todo": "Por hacer", "col_doing": "En curso", "col_done": "Hecho",
        "th_task": "Tarea", "th_assignee": "Asignado", "th_due": "Vence",
        "th_name": "Nombre", "th_qty": "Cant.", "th_planned": "Previsto", "th_actual": "Real",
        "th_supplier": "Proveedor", "th_date": "Fecha", "th_hours": "Horas", "th_note": "Nota",
        "th_number": "N.º", "th_title": "Título", "th_net": "Neto", "th_gross": "Bruto",
        "th_label": "Hito", "th_amount": "Importe", "th_reference": "Referencia",
        "fin_revenue": "Ingresos (presupuesto)", "fin_extras": "Extras aprobados",
        "fin_new_total": "Nuevo total del proyecto", "fin_materials": "Materiales (real)",
        "fin_labour": "Mano de obra", "fin_profit": "Beneficio (est.)", "fin_margin": "Margen",
        "labour_detail": "{h} h × {r}/h",
        "status_active": "Activo", "status_on_hold": "En pausa", "status_done": "Finalizado",
        "status_archived": "Archivado",
        "co_sent": "Enviado", "co_approved": "Aprobado", "co_rejected": "Rechazado", "co_invoiced": "Facturado",
        "pay_requested": "Solicitado", "pay_client_marked_paid": "Marcado pagado", "pay_paid": "Pagado",
        "none": "—", "no_items": "Sin entradas.",
        "footer": "Expediente del trabajo — generado por ServiceMarket",
        "total_hours": "Total de horas registradas",
    },
}


def _L(lang: str) -> dict[str, str]:
    return LABELS.get(lang, LABELS["en"])


# ──────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────
def _extract_file_id(src: Any) -> Optional[str]:
    """Accepts a GridFS file_id, a raw {file_id} dict or a '/api/uploads/<id>'
    URL and returns the bare id string (or None)."""
    if not src:
        return None
    if isinstance(src, dict):
        src = src.get("file_id") or src.get("id") or src.get("url")
    if not isinstance(src, str):
        return None
    return src.rstrip("/").split("/")[-1].strip() or None


async def _fetch_image_bytes(file_id: str) -> Optional[bytes]:
    try:
        stream = await fs_bucket.open_download_stream(ObjectId(file_id))
        return await stream.read()
    except Exception:
        return None


def _fmt_date(dt: Any, lang: str) -> str:
    if not dt:
        return _L(lang)["none"]
    if isinstance(dt, str):
        try:
            dt = datetime.fromisoformat(dt.replace("Z", "+00:00"))
        except Exception:
            return dt
    if isinstance(dt, datetime):
        return dt.strftime("%d.%m.%Y")
    return str(dt)


def _img_flowable(raw: bytes, box_w_mm: float, box_h_mm: float):
    """Normalise (EXIF rotate + RGB) an image and return a reportlab Image
    flowable scaled to fit a box while preserving aspect ratio. Returns None
    if the bytes are not a decodable image."""
    from reportlab.platypus import Image as RLImage
    from reportlab.lib.units import mm
    try:
        from PIL import Image as PILImage, ImageOps
        pim = PILImage.open(BytesIO(raw))
        pim = ImageOps.exif_transpose(pim)
        if pim.mode not in ("RGB", "L"):
            pim = pim.convert("RGB")
        iw, ih = pim.size
        out = BytesIO()
        pim.save(out, format="JPEG", quality=80)
        out.seek(0)
    except Exception:
        return None
    if iw <= 0 or ih <= 0:
        return None
    box_w, box_h = box_w_mm * mm, box_h_mm * mm
    ratio = min(box_w / iw, box_h / ih)
    return RLImage(out, width=iw * ratio, height=ih * ratio)


# ──────────────────────────────────────────────
# Main entry — gather + render
# ──────────────────────────────────────────────
async def generate_job_file_pdf(proj: dict, lang: str = "en") -> bytes:
    lang = lang if lang in SUPPORTED_LANGS else "en"
    L = _L(lang)
    pid = str(proj["_id"])
    pro_id = proj["pro_id"]

    # ── Pro + customer snapshots ─────────────────────────────────────────
    try:
        pro_snap = await get_pro_snapshot(pro_id)
    except Exception:
        pro_snap = {}
    homeowner = None
    if (proj.get("customer") or {}).get("homeowner_id"):
        try:
            homeowner = await db.users.find_one({"_id": ObjectId(proj["customer"]["homeowner_id"])})
        except Exception:
            homeowner = None
    cust = {
        "name": (homeowner or {}).get("name") or (proj.get("customer") or {}).get("name") or L["none"],
        "city": (homeowner or {}).get("city") or (proj.get("customer") or {}).get("city") or "",
        "address": (homeowner or {}).get("address") or "",
    }

    # ── Tasks grouped by column ──────────────────────────────────────────
    tasks_by_col: dict[str, list] = {"todo": [], "doing": [], "done": []}
    async for tdoc in db.pm_tasks.find({"project_id": pid}).sort([("column", 1), ("order", 1)]):
        col = tdoc.get("column", "todo")
        tasks_by_col.setdefault(col, []).append(tdoc)

    # ── Materials (+ collect their photo file ids) ───────────────────────
    materials: list = []
    material_photo_ids: list = []
    async for m in db.pm_materials.find({"project_id": pid}).sort("created_at", 1):
        materials.append(m)
        for ph in (m.get("photos") or []):
            fid = _extract_file_id(ph)
            if fid:
                material_photo_ids.append(fid)

    # ── Diary ────────────────────────────────────────────────────────────
    diary: list = []
    total_hours = 0.0
    async for d in db.pm_diary.find({"project_id": pid}).sort("entry_date", -1):
        diary.append(d)
        total_hours += float(d.get("hours") or 0)

    # ── Change orders ────────────────────────────────────────────────────
    change_orders: list = []
    approved_extras = 0.0
    async for co in db.pm_change_orders.find(
        {"project_id": pid, "status": {"$in": ["sent", "approved", "rejected", "invoiced"]}}
    ).sort("created_at", 1):
        if co.get("status") in ("approved", "invoiced"):
            approved_extras += float(co.get("net_total") or 0)
        change_orders.append(co)

    # ── Payments ─────────────────────────────────────────────────────────
    payments: list = []
    async for pay in db.pm_payment_requests.find({"project_id": pid}).sort("created_at", 1):
        payments.append(pay)

    # ── Financials / P&L ─────────────────────────────────────────────────
    materials_actual = sum(float(m.get("actual_cost") or m.get("planned_cost") or 0) for m in materials)
    quote_total = float(proj.get("quote_price_eur") or 0)
    hourly_rate = float(proj.get("hourly_rate_eur", 65.0))
    labour_cost = round(total_hours * hourly_rate, 2)
    new_total = round(quote_total + approved_extras, 2)
    profit = round(new_total - materials_actual - labour_cost, 2)
    margin = round(profit / new_total * 100, 1) if new_total > 0 else 0.0

    # ── Photos: job progress photos + material photos ────────────────────
    photo_ids: list = []
    try:
        job = await db.jobs.find_one({"_id": ObjectId(proj["job_id"])})
    except Exception:
        job = None
    for p in ((job or {}).get("photos") or []):
        fid = _extract_file_id(p)
        if fid:
            photo_ids.append(fid)
    photo_ids.extend(material_photo_ids)
    # de-dupe preserving order, cap
    seen = set()
    photo_ids = [x for x in photo_ids if not (x in seen or seen.add(x))][:MAX_PHOTOS]
    photo_flowables = []
    for fid in photo_ids:
        raw = await _fetch_image_bytes(fid)
        if raw:
            fl = _img_flowable(raw, 55, 42)
            if fl is not None:
                photo_flowables.append(fl)

    logo_bytes = None
    if pro_snap.get("logo_file_id"):
        logo_bytes = await _fetch_image_bytes(_extract_file_id(pro_snap["logo_file_id"]))

    return _render(
        lang=lang, L=L, proj=proj, pro_snap=pro_snap, cust=cust,
        tasks_by_col=tasks_by_col, materials=materials, diary=diary,
        total_hours=round(total_hours, 2), change_orders=change_orders,
        payments=payments, hourly_rate=hourly_rate, quote_total=quote_total,
        approved_extras=round(approved_extras, 2), new_total=new_total,
        materials_actual=round(materials_actual, 2), labour_cost=labour_cost,
        profit=profit, margin=margin, photo_flowables=photo_flowables,
        logo_bytes=logo_bytes,
    )


# ──────────────────────────────────────────────
# Rendering (sync — pure reportlab)
# ──────────────────────────────────────────────
def _render(*, lang, L, proj, pro_snap, cust, tasks_by_col, materials, diary,
            total_hours, change_orders, payments, hourly_rate, quote_total,
            approved_extras, new_total, materials_actual, labour_cost, profit,
            margin, photo_flowables, logo_bytes) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, KeepTogether,
    )

    TEAL = colors.HexColor("#0F766E")
    HEAD_BG = colors.HexColor("#E8F1F5")
    GRID = colors.HexColor("#CCCCCC")

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=15 * mm, bottomMargin=16 * mm,
        title=f"{L['doc_title']} — {proj.get('title', '')}",
        author=pro_snap.get("business_name") or pro_snap.get("name", ""),
    )
    styles = getSampleStyleSheet()
    s_body = ParagraphStyle("body", parent=styles["Normal"], fontName="Helvetica", fontSize=9, leading=12)
    s_small = ParagraphStyle("small", parent=s_body, fontSize=7.5, textColor=colors.HexColor("#666"))
    s_cell = ParagraphStyle("cell", parent=s_body, fontSize=8, leading=10)
    s_h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=20, leading=23, textColor=TEAL, spaceAfter=2)
    s_h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=12, leading=15, textColor=colors.HexColor("#222"), spaceBefore=8, spaceAfter=4)

    el: list[Any] = []

    def section(title: str):
        el.append(Spacer(1, 3 * mm))
        el.append(Paragraph(f"<b>{title}</b>", s_h2))
        el.append(Table([[""]], colWidths=[174 * mm], rowHeights=[1],
                         style=TableStyle([("LINEABOVE", (0, 0), (-1, 0), 0.8, TEAL)])))
        el.append(Spacer(1, 2 * mm))

    def basic_table(rows, col_widths, align_right_from=None):
        tbl = Table(rows, colWidths=col_widths, repeatRows=1)
        style = [
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("BACKGROUND", (0, 0), (-1, 0), HEAD_BG),
            ("BOX", (0, 0), (-1, -1), 0.5, GRID),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, GRID),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]
        if align_right_from is not None:
            style.append(("ALIGN", (align_right_from, 1), (-1, -1), "RIGHT"))
        tbl.setStyle(TableStyle(style))
        return tbl

    # ── Header (logo + business) ─────────────────────────────────────────
    logo_cell = ""
    if logo_bytes:
        fl = _img_flowable(logo_bytes, 38, 20)
        if fl is not None:
            logo_cell = fl
    biz_line = " · ".join(filter(None, [
        pro_snap.get("business_name") or pro_snap.get("name", ""),
        pro_snap.get("address", ""),
        " ".join(filter(None, [pro_snap.get("postal_code", ""), pro_snap.get("city", "")])),
    ]))
    header_tbl = Table(
        [[Paragraph(f"<b>{L['doc_title']}</b>", s_h1), logo_cell]],
        colWidths=[130 * mm, 44 * mm],
    )
    header_tbl.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("ALIGN", (1, 0), (1, 0), "RIGHT")]))
    el.append(header_tbl)
    el.append(Paragraph(biz_line, s_small))
    el.append(Paragraph(
        f"{L['generated_on']}: {datetime.now(timezone.utc).strftime('%d.%m.%Y')}", s_small))
    el.append(Spacer(1, 5 * mm))

    # ── Summary ──────────────────────────────────────────────────────────
    status_label = L.get(f"status_{proj.get('status', 'done')}", proj.get("status", ""))
    summary_rows = [
        [Paragraph(f"<b>{L['project']}</b>", s_cell), Paragraph(proj.get("title") or proj.get("job_title") or L["none"], s_cell)],
        [Paragraph(f"<b>{L['status']}</b>", s_cell), Paragraph(status_label, s_cell)],
        [Paragraph(f"<b>{L['category']}</b>", s_cell), Paragraph(proj.get("job_category") or L["none"], s_cell)],
        [Paragraph(f"<b>{L['customer']}</b>", s_cell), Paragraph(" · ".join(filter(None, [cust["name"], cust["city"]])) or L["none"], s_cell)],
        [Paragraph(f"<b>{L['tradesperson']}</b>", s_cell), Paragraph(pro_snap.get("business_name") or pro_snap.get("name") or L["none"], s_cell)],
        [Paragraph(f"<b>{L['created']}</b>", s_cell), Paragraph(_fmt_date(proj.get("created_at"), lang), s_cell)],
        [Paragraph(f"<b>{L['completed']}</b>", s_cell), Paragraph(_fmt_date(proj.get("updated_at"), lang), s_cell)],
    ]
    sum_tbl = Table(summary_rows, colWidths=[40 * mm, 134 * mm])
    sum_tbl.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, GRID),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, GRID),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#FAFAF7")),
        ("LEFTPADDING", (0, 0), (-1, -1), 5), ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    section(L["sec_summary"])
    el.append(sum_tbl)

    # ── Tasks ────────────────────────────────────────────────────────────
    section(L["sec_tasks"])
    col_order = [("done", L["col_done"]), ("doing", L["col_doing"]), ("todo", L["col_todo"])]
    any_task = any(tasks_by_col.get(c) for c, _ in col_order)
    if not any_task:
        el.append(Paragraph(L["no_items"], s_small))
    for col_key, col_label in col_order:
        items = tasks_by_col.get(col_key) or []
        if not items:
            continue
        rows = [[L["th_task"], L["th_assignee"], L["th_due"]]]
        for tdoc in items:
            rows.append([
                Paragraph(tdoc.get("title", ""), s_cell),
                Paragraph(tdoc.get("assignee") or L["none"], s_cell),
                Paragraph(_fmt_date(tdoc.get("due_at"), lang), s_cell),
            ])
        el.append(Paragraph(f"<b>{col_label}</b> ({len(items)})", s_body))
        el.append(Spacer(1, 1 * mm))
        el.append(basic_table(rows, [108 * mm, 40 * mm, 26 * mm]))
        el.append(Spacer(1, 2 * mm))

    # ── Materials ────────────────────────────────────────────────────────
    section(L["sec_materials"])
    if not materials:
        el.append(Paragraph(L["no_items"], s_small))
    else:
        rows = [[L["th_name"], L["th_qty"], L["th_planned"], L["th_actual"], L["th_supplier"]]]
        for m in materials:
            rows.append([
                Paragraph(m.get("name", ""), s_cell),
                Paragraph(f"{m.get('qty', 1):g} {m.get('unit', '')}".strip(), s_cell),
                Paragraph(_fmt_eur(float(m.get("planned_cost") or 0)), s_cell),
                Paragraph(_fmt_eur(float(m.get("actual_cost") or 0)) if m.get("actual_cost") is not None else L["none"], s_cell),
                Paragraph(m.get("supplier") or L["none"], s_cell),
            ])
        el.append(basic_table(rows, [62 * mm, 26 * mm, 28 * mm, 28 * mm, 30 * mm], align_right_from=2))

    # ── Diary ────────────────────────────────────────────────────────────
    section(L["sec_diary"])
    if not diary:
        el.append(Paragraph(L["no_items"], s_small))
    else:
        rows = [[L["th_date"], L["th_hours"], L["th_note"]]]
        for d in diary:
            rows.append([
                Paragraph(_fmt_date(d.get("entry_date"), lang), s_cell),
                Paragraph(f"{float(d.get('hours') or 0):g}", s_cell),
                Paragraph(d.get("note", ""), s_cell),
            ])
        el.append(basic_table(rows, [26 * mm, 18 * mm, 130 * mm]))
        el.append(Spacer(1, 1.5 * mm))
        el.append(Paragraph(f"<b>{L['total_hours']}:</b> {total_hours:g} h", s_body))

    # ── Change orders ────────────────────────────────────────────────────
    section(L["sec_change_orders"])
    if not change_orders:
        el.append(Paragraph(L["no_items"], s_small))
    else:
        rows = [[L["th_number"], L["th_title"], L["status"], L["th_net"], L["th_gross"]]]
        for co in change_orders:
            rows.append([
                Paragraph(str(co.get("number") or ""), s_cell),
                Paragraph(co.get("title", ""), s_cell),
                Paragraph(L.get(f"co_{co.get('status', '')}", co.get("status", "")), s_cell),
                Paragraph(_fmt_eur(float(co.get("net_total") or 0)), s_cell),
                Paragraph(_fmt_eur(float(co.get("brutto_total") or 0)), s_cell),
            ])
        el.append(basic_table(rows, [18 * mm, 70 * mm, 28 * mm, 29 * mm, 29 * mm], align_right_from=3))

    # ── Payments ─────────────────────────────────────────────────────────
    section(L["sec_payments"])
    if not payments:
        el.append(Paragraph(L["no_items"], s_small))
    else:
        rows = [[L["th_label"], L["th_reference"], L["th_amount"], L["status"]]]
        for pay in payments:
            rows.append([
                Paragraph(pay.get("label", ""), s_cell),
                Paragraph(pay.get("reference") or L["none"], s_cell),
                Paragraph(_fmt_eur(float(pay.get("amount_eur") or 0)), s_cell),
                Paragraph(L.get(f"pay_{pay.get('status', '')}", pay.get("status", "")), s_cell),
            ])
        el.append(basic_table(rows, [55 * mm, 55 * mm, 30 * mm, 34 * mm], align_right_from=2))

    # ── Financials ───────────────────────────────────────────────────────
    section(L["sec_financials"])
    fin_rows = [
        [L["fin_revenue"], _fmt_eur(quote_total)],
        [L["fin_extras"], f"+ {_fmt_eur(approved_extras)}"],
        [L["fin_new_total"], _fmt_eur(new_total)],
        [L["fin_materials"], f"- {_fmt_eur(materials_actual)}"],
        [f"{L['fin_labour']} ({L['labour_detail'].format(h=f'{total_hours:g}', r=_fmt_eur(hourly_rate))})", f"- {_fmt_eur(labour_cost)}"],
        [f"{L['fin_profit']} ({L['fin_margin']} {margin:g}%)", _fmt_eur(profit)],
    ]
    fin_tbl = Table(fin_rows, colWidths=[120 * mm, 54 * mm])
    fin_tbl.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("LINEABOVE", (0, 2), (-1, 2), 0.5, GRID),
        ("LINEABOVE", (0, -1), (-1, -1), 0.8, colors.black),
        ("FONTNAME", (0, 2), (-1, 2), "Helvetica-Bold"),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    el.append(fin_tbl)

    # ── Photos ───────────────────────────────────────────────────────────
    if photo_flowables:
        section(L["sec_photos"])
        per_row = 3
        grid_rows = []
        for i in range(0, len(photo_flowables), per_row):
            chunk = photo_flowables[i:i + per_row]
            while len(chunk) < per_row:
                chunk.append("")
            grid_rows.append(chunk)
        photo_tbl = Table(grid_rows, colWidths=[58 * mm] * per_row)
        photo_tbl.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        el.append(photo_tbl)

    # ── Footer note ──────────────────────────────────────────────────────
    el.append(Spacer(1, 6 * mm))
    el.append(Paragraph(f"<i>{L['footer']}</i>", s_small))

    doc.build(el)
    return buf.getvalue()
