"""Elektrik in depth — 16 job types with guided forms.

Bands from AT price radars: Elektriker 55-110 EUR/h (some sources 68-115),
E-Befund 150-350, Verteilertausch 800-2.500, Wallbox 500-1.500 installiert
(3-6 h). (fixbuddy.at, werkflow.at, daibau.at, wallbox-kosten.at)

Every job carries a note about the E-Befund. Electrical work in existing
fabric touches a legally significant document, and a quote that is silent
about it leaves the pro carrying a risk they did not price.
"""
from schema import JobType as J, Operation as Op, Question as Q

G, S = "Elektrik", "Elektriker"
SRC = ["fixbuddy.at/was-kostet-elektriker", "werkflow.at/elektriker-kosten",
       "daibau.at/baukostenrechner/elektroinstallationen"]

Q_ZUGANG = Q("access", "Zugang", "choice", affects="access",
             options=[("eg_oder_lift", "Erdgeschoss oder Lift"),
                      ("og_ohne_lift", "Obergeschoss ohne Lift"),
                      ("enge_treppe", "Enge Treppe")], default="eg_oder_lift")
Q_BEWOHNT = Q("condition", "Zustand", "choice", affects="condition",
              options=[("neubau", "Neubau, leer"),
                       ("renovierung_leer", "Renovierung, leer"),
                       ("renovierung_bewohnt", "Renovierung, bewohnt"),
                       ("altbau_bewohnt", "Altbau, bewohnt")],
              default="renovierung_leer")
Q_BAUJAHR = Q("baujahr", "Baujahr", "number", unit="Jahr", affects="note",
              help_de="Vor 1965: oft ohne Schutzleiter. Vor 1990: kein FI.")
Q_ALTANLAGE = Q("altanlage", "Zustand der Bestandsanlage", "choice", affects="note",
                options=[("modern", "Modern, mit FI"),
                         ("mit_pe", "Älter, aber mit Schutzleiter"),
                         ("klassisch_null", "Klassische Nullung / kein PE"),
                         ("unbekannt", "Unbekannt")],
                default="unbekannt",
                note_if={"klassisch_null": "klassische_nullung",
                         "unbekannt": "altanlage_unbekannt"})

ELEKTRIK_DEEP = [
    # ── Störung und Notdienst ─────────────────────────────────────────
    J(key="elektrik.stoerungssuche", trade="elektrik", group=G, segment=S,
      messy=False, label_de="Störungssuche und Behebung", unit="Stk",
      setup_hours=(0.5, 0.9), typical_size=(1, 1),
      market_band_at=(140, 380), market_band_de=(150, 400), band_basis="total",
      confidence="medium", emergency_capable=True, sources=SRC,
      note_keys=["e_befund", "folgearbeiten_nach_aufwand"],
      guided_form=[
          Q("symptom", "Symptom", "choice", affects="variant",
            options=[("fi_faellt", "FI fällt"), ("kein_strom", "Kein Strom in einem Raum"),
                     ("teilausfall", "Teilausfall"), ("flackern", "Flackern")],
            default="fi_faellt"),
          Q("zeit", "Einsatzzeit", "choice", affects="variant",
            options=[("regulaer", "Werktag"), ("nacht_sonntag", "Nacht/Sonntag")],
            default="regulaer", note_if={"nacht_sonntag": "nacht_zuschlag"}),
          Q_ALTANLAGE],
      operations=[Op("anfahrt", "Anfahrt", "Stk", (0.3, 0.6), kind="travel"),
                  Op("messung", "Messtechnische Eingrenzung", "Stk", (0.6, 1.2)),
                  Op("behebung", "Behebung im Rahmen der Erstmaßnahme", "Stk", (0.4, 0.85),
                     material_per_unit=(15, 60))]),

    # ── Prüfung — the recurring, legally mandated revenue ─────────────
    J(key="elektrik.e_befund", trade="elektrik", group=G, segment=S, messy=False,
      label_de="E-Befund / Anlagenüberprüfung", unit="Stk",
      setup_hours=(0.3, 0.6), typical_size=(1, 1),
      market_band_at=(150, 350), market_band_de=(160, 380), band_basis="total",
      confidence="high", sources=SRC,
      note_keys=["befund_maengel_extra", "befund_intervall"],
      guided_form=[
          Q("objekt", "Objekt", "choice", affects="variant",
            options=[("wohnung", "Wohnung"), ("haus", "Einfamilienhaus"),
                     ("gewerbe", "Gewerbeobjekt")], default="wohnung"),
          Q("stromkreise", "Anzahl Stromkreise", "number", unit="Stk", default=12,
            affects="qty"),
          Q("anlass", "Anlass", "choice", affects="note",
            options=[("verkauf", "Verkauf/Vermietung"), ("periodisch", "Periodisch"),
                     ("schaden", "Nach Schaden")],
            note_if={"verkauf": "befund_uebergabe"})],
      operations=[Op("sichtpruefung", "Sichtprüfung", "Stk", (0.4, 0.8)),
                  Op("messung", "Messungen nach ÖVE/ÖNORM E 8001 bzw. DIN VDE 0100-600",
                     "Stk", (0.8, 1.4)),
                  Op("protokoll", "Befund und Protokoll", "Stk", (0.3, 0.6))]),

    J(key="elektrik.geraetepruefung", trade="elektrik", group=G, segment=S,
      messy=False, label_de="Prüfung ortsveränderlicher Geräte", unit="Stk",
      setup_hours=(0.4, 0.8), typical_size=(10, 60),
      market_band_at=(6, 18), market_band_de=(6, 20), confidence="medium",
      sources=SRC, note_keys=["befund_intervall", "pruefplakette"],
      guided_form=[Q("anzahl", "Anzahl Geräte", "number", unit="Stk", default=25,
                     affects="qty")],
      operations=[Op("pruefung", "Prüfung und Kennzeichnung", "Stk", (0.06, 0.14)),
                  Op("protokoll", "Prüfprotokoll", "Stk", (0.01, 0.03))]),

    # ── Kleininstallation ─────────────────────────────────────────────
    J(key="elektrik.schalter_tauschen", trade="elektrik", group=G, segment=S,
      messy=False, label_de="Schalter oder Steckdose tauschen", unit="Stk",
      setup_hours=(0.3, 0.6), typical_size=(1, 8),
      market_band_at=(45, 120), market_band_de=(48, 130), band_basis="total",
      confidence="medium", sources=SRC, note_keys=["e_befund"],
      guided_form=[Q("anzahl", "Anzahl", "number", unit="Stk", default=1, affects="qty"),
                   Q_ALTANLAGE],
      operations=[Op("tausch", "Einsatz tauschen und prüfen", "Stk", (0.25, 0.45)),
                  Op("material", "Einsatz und Abdeckung", "Stk", (0.0, 0.0),
                     kind="material", material_per_unit=(9, 28))]),

    J(key="elektrik.leuchte_montieren", trade="elektrik", group=G, segment=S,
      messy=False, label_de="Leuchte montieren", unit="Stk",
      setup_hours=(0.3, 0.6), typical_size=(1, 6),
      market_band_at=(55, 160), market_band_de=(58, 170), band_basis="total",
      confidence="medium", sources=SRC, note_keys=["untergrund_tragfaehig"],
      guided_form=[Q("art", "Art", "choice", affects="variant",
                     options=[("deckenleuchte", "Deckenleuchte"),
                              ("haengeleuchte", "Hängeleuchte"),
                              ("spots", "Einbauspots")], default="deckenleuchte"),
                   Q("anzahl", "Anzahl", "number", unit="Stk", default=1, affects="qty"),
                   Q("hoehe", "Raumhöhe über 3 m?", "bool", affects="note",
                     default=False, note_if={True: "arbeitsbuehne"})],
      operations=[Op("montage", "Montieren und anschließen", "Stk", (0.4, 0.9)),
                  Op("material", "Kleinmaterial", "Stk", (0.0, 0.0), kind="material",
                     material_per_unit=(5, 18))]),

    J(key="elektrik.rauchmelder", trade="elektrik", group=G, segment=S, messy=False,
      label_de="Rauchwarnmelder montieren", unit="Stk",
      setup_hours=(0.18, 0.32), typical_size=(2, 8),
      market_band_at=(35, 95), market_band_de=(38, 100), band_basis="total",
      confidence="medium", sources=SRC, note_keys=["rauchmelder_pflicht"],
      guided_form=[Q("anzahl", "Anzahl Räume", "number", unit="Stk", default=3,
                     affects="qty"),
                   Q("vernetzt", "Funkvernetzt?", "bool", affects="variant",
                     default=False)],
      operations=[Op("montage", "Montage und Funktionstest", "Stk", (0.14, 0.26)),
                  Op("melder", "Rauchwarnmelder", "Stk", (0.0, 0.0), kind="material",
                     material_per_unit=(18, 55))]),

    J(key="elektrik.aussensteckdose", trade="elektrik", group=G, segment=S,
      label_de="Außensteckdose setzen (IP44)", unit="Stk",
      setup_hours=(0.4, 0.8), typical_size=(1, 3),
      market_band_at=(180, 450), market_band_de=(190, 480), band_basis="total",
      confidence="low", sources=SRC, note_keys=["e_befund", "mauerdurchbruch"],
      guided_form=[Q("durchbruch", "Wanddurchführung nötig?", "bool",
                     affects="variant", default=True),
                   Q("entfernung", "Entfernung zum Verteiler", "number", unit="lfm",
                     default=6, affects="qty")],
      operations=[Op("durchfuehrung", "Wanddurchführung herstellen", "Stk", (0.5, 1.0),
                     debris_kg_per_unit=(3, 10)),
                  Op("leitung", "Zuleitung verlegen", "Stk", (0.55, 1.0),
                     material_per_unit=(15, 40)),
                  Op("dose", "Dose setzen und anschließen", "Stk", (0.4, 0.8),
                     material_per_unit=(22, 55))]),

    J(key="elektrik.herdanschluss", trade="elektrik", group=G, segment=S,
      messy=False, label_de="Herd- oder Kochfeldanschluss", unit="Stk",
      setup_hours=(0.3, 0.6), typical_size=(1, 1),
      market_band_at=(90, 260), market_band_de=(95, 280), band_basis="total",
      confidence="medium", sources=SRC, note_keys=["e_befund", "anschluss_konzessioniert"],
      guided_form=[Q("vorhanden", "Herdanschlussdose vorhanden?", "bool",
                     affects="variant", default=True,
                     note_if={False: "neue_zuleitung_noetig"})],
      operations=[Op("anschluss", "Anschließen und prüfen", "Stk", (0.6, 1.2),
                     material_per_unit=(12, 35))]),

    J(key="elektrik.datendose", trade="elektrik", group=G, segment=S,
      label_de="Netzwerkdose setzen (Cat 6a)", unit="Stk",
      setup_hours=(0.3, 0.55), typical_size=(1, 8),
      market_band_at=(120, 320), market_band_de=(130, 340), band_basis="total",
      confidence="low", sources=SRC, note_keys=["messprotokoll_netzwerk"],
      guided_form=[Q("anzahl", "Anzahl Dosen", "number", unit="Stk", default=2,
                     affects="qty"),
                   Q("laenge", "Durchschnittliche Leitungslänge", "number", unit="lfm",
                     default=12, affects="qty"),
                   Q_BEWOHNT],
      operations=[Op("leitung", "Datenleitung verlegen", "Stk", (0.45, 0.85),
                     material_per_unit=(14, 35)),
                  Op("dose", "Dose setzen und auflegen", "Stk", (0.28, 0.50),
                     material_per_unit=(18, 45)),
                  Op("messung", "Messung und Protokoll", "Stk", (0.2, 0.4))]),

    # ── Wallbox und E-Mobilität — the growth segment ──────────────────
    J(key="elektrik.wallbox", trade="elektrik", group=G, segment=S,
      label_de="Wallbox installieren (11 kW)", unit="Stk",
      setup_hours=(0.6, 1.2), typical_size=(1, 1),
      market_band_at=(500, 1500), market_band_de=(550, 1600), band_basis="total",
      confidence="high", sources=["wallbox-kosten.at/wallbox-kosten/installation"],
      note_keys=["netzbetreiber_meldung", "fi_typ_b", "foerderung",
                 "lastmanagement"],
      guided_form=[
          Q("entfernung", "Entfernung Verteiler zur Wallbox", "number", unit="lfm",
            default=10, affects="qty",
            help_de="Der größte Kostentreiber. Über 20 m wird die Zuleitung teuer."),
          Q("verlegung", "Verlegeart", "choice", affects="variant",
            options=[("aufputz", "Aufputz / Kabelkanal"), ("unterputz", "Unterputz"),
                     ("erdverlegt", "Erdverlegt (Garage separat)")],
            default="aufputz", note_if={"erdverlegt": "erdarbeiten_extra"}),
          Q("verteiler_platz", "Platz im Verteiler frei?", "bool", affects="note",
            default=True, note_if={False: "verteiler_erweiterung"}),
          Q("fi_vorhanden", "FI Typ A/B vorhanden?", "bool", affects="note",
            default=False, note_if={False: "fi_typ_b"})],
      operations=[Op("zuleitung", "Zuleitung verlegen", "Stk", (1.5, 3.0),
                     material_per_unit=(90, 220)),
                  Op("absicherung", "Absicherung und FI im Verteiler", "Stk", (0.8, 1.6),
                     material_per_unit=(120, 280)),
                  Op("montage", "Wallbox montieren und anschließen", "Stk", (1.0, 2.0)),
                  Op("inbetriebnahme", "Inbetriebnahme, Messung, Anmeldung", "Stk",
                     (0.8, 1.5))]),

    # ── Verteiler und Sanierung ──────────────────────────────────────
    J(key="elektrik.verteiler_klein", trade="elektrik", group=G, segment=S,
      label_de="Verteiler erweitern (einzelne Stromkreise)", unit="Stk",
      setup_hours=(0.5, 1.0), typical_size=(1, 1),
      market_band_at=(220, 650), market_band_de=(240, 700), band_basis="total",
      confidence="medium", sources=SRC, note_keys=["abschaltung", "e_befund"],
      guided_form=[Q("stromkreise", "Neue Stromkreise", "number", unit="Stk",
                     default=2, affects="qty"),
                   Q("platz", "Platz im Verteiler?", "bool", affects="note",
                     default=True, note_if={False: "verteiler_erweiterung"})],
      operations=[Op("montage", "Automaten und FI ergänzen", "Stk", (0.8, 1.6),
                     material_per_unit=(45, 130)),
                  Op("pruefung", "Prüfung und Beschriftung", "Stk", (0.4, 0.8))]),

    J(key="elektrik.wohnung_neuinstallation", trade="elektrik", group=G, segment=S,
      label_de="Elektroinstallation Wohnung komplett", unit="m2",
      setup_hours=(3.0, 6.0), typical_size=(50, 120),
      market_band_at=(85, 180), market_band_de=(90, 190), confidence="medium",
      sources=SRC, note_keys=["e_befund", "staub", "koordination_gewerke",
                              "abschaltung"],
      guided_form=[
          Q("wohnflaeche", "Wohnfläche", "number", unit="m2", default=75, affects="qty"),
          Q_BEWOHNT, Q_BAUJAHR, Q_ALTANLAGE,
          Q("ausstattung", "Ausstattungsgrad", "choice", affects="variant",
            options=[("basic", "Standard"), ("standard", "Gehoben"),
                     ("premium", "Smart Home")], default="standard")],
      operations=[Op("schlitze", "Schlitze und Dosen", "m2", (0.22, 0.40),
                     debris_kg_per_unit=(6, 14)),
                  Op("leitungen", "Leitungen verlegen", "m2", (0.20, 0.36),
                     material_per_unit=(7, 15)),
                  Op("verteiler", "Verteiler neu", "m2", (0.06, 0.12),
                     material_per_unit=(6, 14)),
                  Op("geraete", "Schalter, Steckdosen, Auslässe", "m2", (0.14, 0.26),
                     material_per_unit=(9, 22)),
                  Op("verschliessen", "Schlitze verschließen", "m2", (0.14, 0.26),
                     material_per_unit=(2, 5)),
                  Op("pruefung", "Messung, Befund, Übergabe", "m2", (0.05, 0.10))]),

    J(key="elektrik.smarthome", trade="elektrik", group=G, segment=S, messy=False,
      label_de="Smart-Home-Nachrüstung (Schalter/Jalousie)", unit="Stk",
      setup_hours=(0.5, 1.0), typical_size=(3, 15),
      market_band_at=(110, 300), market_band_de=(120, 320), band_basis="total",
      confidence="low", sources=SRC, note_keys=["neutralleiter_noetig", "system_bindung"],
      guided_form=[Q("anzahl", "Anzahl Punkte", "number", unit="Stk", default=6,
                     affects="qty"),
                   Q("neutral", "Neutralleiter in der Dose vorhanden?", "choice",
                     affects="note",
                     options=[("ja", "Ja"), ("nein", "Nein"), ("unbekannt", "Unbekannt")],
                     default="unbekannt",
                     note_if={"nein": "neutralleiter_noetig",
                              "unbekannt": "neutralleiter_noetig"})],
      operations=[Op("montage", "Aktoren setzen und einlernen", "Stk", (0.38, 0.75)),
                  Op("material", "Aktor und Bedienteil", "Stk", (0.0, 0.0),
                     kind="material", material_per_unit=(55, 150)),
                  Op("konfiguration", "System konfigurieren", "Stk", (0.2, 0.5))]),

    J(key="elektrik.gegensprechanlage", trade="elektrik", group=G, segment=S,
      label_de="Gegensprech-/Videoanlage tauschen", unit="Stk",
      setup_hours=(0.8, 1.5), typical_size=(1, 1),
      market_band_at=(450, 1400), market_band_de=(480, 1500), band_basis="total",
      confidence="low", sources=SRC, note_keys=["bestandsleitung_nutzbar"],
      guided_form=[Q("parteien", "Anzahl Parteien", "number", unit="Stk", default=1,
                     affects="qty"),
                   Q("leitung", "Bestandsleitung nutzbar?", "choice", affects="note",
                     options=[("ja", "Ja"), ("nein", "Nein"), ("unbekannt", "Unbekannt")],
                     default="unbekannt", note_if={"nein": "neue_leitung_noetig",
                                                   "unbekannt": "bestandsleitung_nutzbar"})],
      operations=[Op("demontage", "Altanlage demontieren", "Stk", (0.6, 1.2),
                     debris_kg_per_unit=(3, 8), debris_type="metall"),
                  Op("anlage", "Anlage inkl. Außenstation", "Stk", (0.0, 0.0),
                     kind="material", material_per_unit=(220, 700)),
                  Op("montage", "Montage und Inbetriebnahme", "Stk", (2.0, 4.0))]),
]
