"""Sanitär in depth — 18 job types with guided forms.

Bands sourced from AT price radars: Installateur 68-112 EUR/h, Notdienst
125-160; Rohrreinigung Waschbecken 80-180, WC 150-300, Kamerabefahrung
120-250; Sanitärerneuerung (WC/Waschtisch/Dusche) 3.500-7.000, Komplettumbau
mit Fliesen 9.000-16.000; Thermenwartung 170-280.
(werkflow.at, daibau.at, gecheckt.at, installateur-hilfe.at)
"""
from schema import JobType as J, Operation as Op, Question as Q

G, S = "Sanitär", "Sanitär- / Klempner"
SRC = ["werkflow.at/installateur-kosten", "daibau.at/baukostenrechner/klempner",
       "gecheckt.at/preise/wasserinstallateure"]

# Questions reused across jobs. Every one changes a number; none are asked for
# decoration.
Q_ZUGANG = Q("access", "Zugang", "choice", affects="access",
             options=[("eg_oder_lift", "Erdgeschoss oder Lift"),
                      ("og_ohne_lift", "Obergeschoss ohne Lift"),
                      ("enge_treppe", "Enge Treppe")], default="eg_oder_lift")
Q_BEWOHNT = Q("condition", "Zustand", "choice", affects="condition",
              options=[("neubau", "Neubau, leer"),
                       ("renovierung_leer", "Renovierung, Wohnung leer"),
                       ("renovierung_bewohnt", "Renovierung, bewohnt"),
                       ("altbau_bewohnt", "Altbau, bewohnt")],
              default="renovierung_leer")
Q_BAUJAHR = Q("baujahr", "Baujahr des Gebäudes", "number", unit="Jahr",
              affects="note", help_de="Vor 1990: Asbest- und Bleiprüfung nötig.")
Q_ABSPERR = Q("absperrventil", "Funktionierendes Absperrventil vorhanden?", "bool",
              affects="note", default=True,
              note_if={False: "kein_absperrventil"},
              help_de="Ohne Absperrventil muss der Steigstrang abgesperrt werden.")

SANITAER_DEEP = [
    # ── Notdienst und Rohrreinigung — the emergency segment ────────────
    J(key="sanitaer.notdienst_anfahrt", messy=False, trade="sanitaer", group=G, segment=S,
      label_de="Notdienst-Anfahrt und Erstdiagnose", unit="Stk",
      setup_hours=(0.3, 0.6), typical_size=(1, 1),
      market_band_at=(120, 260), market_band_de=(125, 280), band_basis="total",
      confidence="high", emergency_capable=True, sources=SRC,
      note_keys=["nacht_zuschlag", "notdienst_pauschale"],
      guided_form=[
          Q("zeit", "Einsatzzeit", "choice", affects="variant",
            options=[("regulaer", "Werktag 7-17 Uhr"), ("abend", "Abend/Samstag"),
                     ("nacht_sonntag", "Nacht oder Sonn-/Feiertag")],
            default="regulaer", note_if={"nacht_sonntag": "nacht_zuschlag"}),
          Q_ZUGANG],
      operations=[Op("anfahrt", "Anfahrt Notdienst", "Stk", (0.5, 0.9), kind="travel"),
                  Op("diagnose", "Erstdiagnose vor Ort", "Stk", (0.4, 0.8))]),

    J(key="sanitaer.rohrreinigung_waschbecken", messy=False, trade="sanitaer", group=G,
      segment="Rohrreinigung", label_de="Verstopfung Waschbecken/Dusche lösen",
      unit="Stk", setup_hours=(0.3, 0.5), typical_size=(1, 1),
      market_band_at=(80, 180), market_band_de=(85, 190), band_basis="total",
      confidence="high", emergency_capable=True, sources=SRC,
      note_keys=["folgeschaeden"],
      guided_form=[
          Q("art", "Was ist verstopft?", "choice", affects="variant",
            options=[("waschbecken", "Waschbecken"), ("dusche", "Dusche/Wanne"),
                     ("kueche", "Küchenspüle")], default="waschbecken"),
          Q("dauer", "Seit wann?", "choice", affects="note",
            options=[("akut", "Seit heute"), ("wiederkehrend", "Wiederkehrend")],
            note_if={"wiederkehrend": "kamera_empfohlen"})],
      operations=[Op("reinigung", "Mechanische Reinigung, Siphon", "Stk", (0.5, 1.0)),
                  Op("material", "Dichtungen, Kleinmaterial", "Stk", (0.0, 0.0),
                     kind="material", material_per_unit=(8, 25))]),

    J(key="sanitaer.rohrreinigung_wc", messy=False, trade="sanitaer", group=G,
      segment="Rohrreinigung", label_de="Verstopfung WC/Fallstrang lösen", unit="Stk",
      setup_hours=(0.3, 0.6), typical_size=(1, 1),
      market_band_at=(150, 300), market_band_de=(155, 320), band_basis="total",
      confidence="high", emergency_capable=True, sources=SRC,
      note_keys=["folgeschaeden", "fremdkoerper"],
      guided_form=[
          Q("umfang", "Betroffen ist", "choice", affects="variant",
            options=[("einzeln", "Nur ein WC"), ("mehrere", "Mehrere Abläufe")],
            default="einzeln", note_if={"mehrere": "fallstrang_verdacht"}),
          Q_ZUGANG],
      operations=[Op("spirale", "Rohrspirale einsetzen", "Stk", (0.8, 1.6)),
                  Op("kontrolle", "Funktionskontrolle und Spülung", "Stk", (0.3, 0.6))]),

    J(key="sanitaer.kamerabefahrung", messy=False, trade="sanitaer", group=G,
      segment="Rohrreinigung", label_de="Kanal-Kamerabefahrung mit Protokoll",
      unit="Stk", setup_hours=(0.4, 0.8), typical_size=(1, 1),
      market_band_at=(120, 250), market_band_de=(130, 270), band_basis="total",
      confidence="high", sources=SRC, note_keys=["protokoll_versicherung"],
      guided_form=[Q("laenge", "Zu befahrende Länge", "number", unit="lfm",
                     affects="note", default=15)],
      operations=[Op("befahrung", "Befahrung und Aufzeichnung", "Stk", (0.6, 1.1)),
                  Op("protokoll", "Protokoll erstellen", "Stk", (0.2, 0.5))]),

    # ── Sanitärobjekte ────────────────────────────────────────────────
    J(key="sanitaer.armatur", messy=False, trade="sanitaer", group=G, segment=S,
      label_de="Armatur tauschen", unit="Stk", setup_hours=(0.3, 0.6),
      typical_size=(1, 3), market_band_at=(130, 320), market_band_de=(140, 340),
      band_basis="total", confidence="medium", sources=SRC,
      note_keys=["absperrventil"], guided_form=[Q_ABSPERR, Q_BAUJAHR],
      operations=[Op("demontage", "Altarmatur demontieren", "Stk", (0.3, 0.6)),
                  Op("montage", "Neue Armatur montieren", "Stk", (0.5, 1.0)),
                  Op("material", "Anschlussschläuche, Dichtungen", "Stk", (0.0, 0.0),
                     kind="material", material_per_unit=(18, 45))]),

    J(key="sanitaer.spuelkasten", messy=False, trade="sanitaer", group=G, segment=S,
      label_de="Spülkasten reparieren (UP)", unit="Stk", setup_hours=(0.3, 0.6),
      typical_size=(1, 1), market_band_at=(150, 380), market_band_de=(160, 400),
      band_basis="total", confidence="medium", sources=SRC,
      note_keys=["ersatzteil_verfuegbarkeit"],
      guided_form=[Q("typ", "Bauart", "choice", affects="variant",
                     options=[("up", "Unterputz (Vorwand)"), ("ap", "Aufputz")],
                     default="up"),
                   Q("hersteller", "Hersteller bekannt?", "bool", affects="note",
                     default=True, note_if={False: "ersatzteil_verfuegbarkeit"})],
      operations=[Op("oeffnen", "Revisionsöffnung, Diagnose", "Stk", (0.4, 0.9)),
                  Op("reparatur", "Spülventil/Füllventil tauschen", "Stk", (0.6, 1.3)),
                  Op("material", "Ersatzteile", "Stk", (0.0, 0.0), kind="material",
                     material_per_unit=(35, 110))]),

    J(key="sanitaer.badewanne_tausch", trade="sanitaer", group=G, segment=S,
      label_de="Badewanne tauschen", unit="Stk", setup_hours=(1.0, 1.8),
      typical_size=(1, 1), market_band_at=(900, 2200), market_band_de=(950, 2400),
      band_basis="total", confidence="medium", sources=SRC,
      note_keys=["fliesen_anschluss", "altgeraet_entsorgung"],
      guided_form=[Q_BEWOHNT, Q_ZUGANG,
                   Q("fliesen", "Fliesen im Anschlussbereich erhalten?", "bool",
                     affects="note", default=False,
                     note_if={True: "fliesen_anschluss"})],
      operations=[Op("demontage", "Altwanne ausbauen", "Stk", (2.0, 3.5),
                     debris_kg_per_unit=(40, 120)),
                  Op("wanne", "Wanne inkl. Träger und Ablauf", "Stk", (0.0, 0.0),
                     kind="material", material_per_unit=(320, 750)),
                  Op("montage", "Einbau, Anschluss, Abdichtung", "Stk", (3.5, 6.0),
                     material_per_unit=(45, 120))]),

    J(key="sanitaer.wanne_zu_dusche", trade="sanitaer", group=G, segment=S,
      label_de="Wanne raus, bodengleiche Dusche rein", unit="Stk",
      setup_hours=(1.5, 2.5), typical_size=(1, 1),
      market_band_at=(2800, 6500), market_band_de=(3000, 7000), band_basis="total",
      confidence="medium", sources=SRC,
      note_keys=["abdichtung_nassbereich", "gefaelle_ablauf", "fliesen_folgt",
                 "foerderung_barrierefrei"],
      guided_form=[Q_BEWOHNT, Q_ZUGANG, Q_BAUJAHR,
                   Q("aufbauhoehe", "Aufbauhöhe für Ablauf ausreichend?", "choice",
                     affects="variant",
                     options=[("ja", "Ja, > 12 cm"), ("nein", "Nein / unbekannt")],
                     default="nein", note_if={"nein": "aufbauhoehe_kritisch"}),
                   Q("barrierefrei", "Barrierefrei nach ÖNORM B 1600?", "bool",
                     affects="note", default=False,
                     note_if={True: "foerderung_barrierefrei"})],
      operations=[Op("demontage", "Wanne und Fliesen entfernen", "Stk", (4.0, 7.0),
                     debris_kg_per_unit=(180, 400)),
                  Op("ablauf", "Ablauf und Gefälle herstellen", "Stk", (3.0, 5.5),
                     material_per_unit=(180, 420)),
                  Op("abdichtung", "Verbundabdichtung", "Stk", (2.0, 3.5),
                     material_per_unit=(90, 190)),
                  Op("dusche", "Duschelemente, Armatur, Tür", "Stk", (0.0, 0.0),
                     kind="material", material_per_unit=(700, 1900)),
                  Op("montage", "Montage und Anschluss", "Stk", (4.0, 7.0))]),

    J(key="sanitaer.duschkabine", messy=False, trade="sanitaer", group=G, segment=S,
      label_de="Duschkabine montieren", unit="Stk", setup_hours=(0.5, 1.0),
      typical_size=(1, 1), market_band_at=(320, 780), market_band_de=(340, 820),
      band_basis="total", confidence="medium", sources=SRC,
      note_keys=["wand_lot", "silikon_wartungsfuge"],
      guided_form=[Q("wand", "Wände lot- und fluchtgerecht?", "bool",
                     affects="note", default=True, note_if={False: "wand_lot"})],
      operations=[Op("montage", "Kabine montieren und ausrichten", "Stk", (2.0, 4.0)),
                  Op("silikon", "Verfugen", "Stk", (0.4, 0.8),
                     material_per_unit=(12, 30))]),

    # ── Warmwasser und Leitungen ──────────────────────────────────────
    J(key="sanitaer.boiler", trade="sanitaer", group=G, segment=S,
      label_de="Warmwasserspeicher tauschen", unit="Stk", setup_hours=(0.8, 1.5),
      typical_size=(1, 1), market_band_at=(750, 1900), market_band_de=(800, 2000),
      band_basis="total", confidence="medium", sources=SRC,
      note_keys=["altgeraet_entsorgung", "elektro_anschluss"],
      guided_form=[Q("liter", "Speichergröße", "number", unit="l", default=120,
                     affects="variant"),
                   Q_ZUGANG,
                   Q("anschluss", "Elektroanschluss vorhanden und ausreichend?",
                     "bool", affects="note", default=True,
                     note_if={False: "elektro_anschluss"})],
      operations=[Op("demontage", "Altgerät entleeren und ausbauen", "Stk", (1.2, 2.2),
                     debris_kg_per_unit=(30, 80), debris_type="metall"),
                  Op("geraet", "Speicher inkl. Sicherheitsgruppe", "Stk", (0.0, 0.0),
                     kind="material", material_per_unit=(380, 900)),
                  Op("montage", "Montage, Anschluss, Inbetriebnahme", "Stk", (2.5, 4.5))]),

    J(key="sanitaer.steigleitung", trade="sanitaer", group=G, segment=S,
      label_de="Wasserleitung erneuern (Strang)", unit="lfm",
      setup_hours=(1.5, 3.0), typical_size=(8, 40),
      market_band_at=(85, 190), market_band_de=(90, 200), confidence="medium",
      sources=SRC, note_keys=["staub", "oeffnung_wand", "bleirohre_vor_1970",
                              "abstimmung_hausgemeinschaft"],
      guided_form=[Q_BAUJAHR, Q_BEWOHNT,
                   Q("verlegung", "Verlegeart", "choice", affects="variant",
                     options=[("unterputz", "Unterputz (stemmen)"),
                              ("aufputz", "Aufputz / Vorwand")],
                     default="unterputz"),
                   Q("material_alt", "Altmaterial", "choice", affects="note",
                     options=[("kunststoff", "Kunststoff"), ("kupfer", "Kupfer"),
                              ("verzinkt", "Verzinkter Stahl"), ("blei", "Blei")],
                     note_if={"blei": "bleirohre_vor_1970"})],
      operations=[Op("stemmen", "Schlitze stemmen", "lfm", (0.25, 0.45),
                     debris_kg_per_unit=(8, 18)),
                  Op("verlegen", "Rohr verlegen und pressen", "lfm", (0.30, 0.55),
                     material_per_unit=(14, 30)),
                  Op("daemmung", "Dämmung nach ÖNORM", "lfm", (0.08, 0.15),
                     material_per_unit=(3, 8)),
                  Op("druckprobe", "Druckprobe und Protokoll", "lfm", (0.05, 0.10)),
                  Op("verschliessen", "Schlitze verschließen", "lfm", (0.20, 0.38),
                     material_per_unit=(3, 7))]),

    J(key="sanitaer.waschmaschinenanschluss", trade="sanitaer", group=G, segment=S,
      label_de="Waschmaschinenanschluss setzen", unit="Stk",
      setup_hours=(0.5, 0.9), typical_size=(1, 1),
      market_band_at=(280, 700), market_band_de=(300, 750), band_basis="total",
      confidence="medium", sources=SRC, note_keys=["oeffnung_wand"],
      guided_form=[Q("entfernung", "Entfernung zur nächsten Leitung", "number",
                     unit="lfm", default=3, affects="qty"),
                   Q_BEWOHNT],
      operations=[Op("leitung", "Zu- und Ablauf herstellen", "Stk", (1.4, 2.8),
                     material_per_unit=(60, 150), debris_kg_per_unit=(15, 40)),
                  Op("armatur", "Geräteanschlussventil und Siphon", "Stk", (0.4, 0.8),
                     material_per_unit=(35, 80))]),

    # ── Wartung und Prüfung — the recurring revenue ───────────────────
    J(key="sanitaer.therme_wartung", messy=False, trade="sanitaer", group=G, segment=S,
      label_de="Thermenwartung (jährlich)", unit="Stk", setup_hours=(0.2, 0.4),
      typical_size=(1, 1), market_band_at=(170, 280), market_band_de=(175, 300),
      band_basis="total", confidence="high", sources=SRC,
      note_keys=["rauchfangkehrer", "wartungsvertrag"],
      guided_form=[Q("typ", "Gerätetyp", "choice", affects="variant",
                     options=[("gas", "Gastherme"), ("brennwert", "Brennwertgerät")],
                     default="gas"),
                   Q("letzte", "Letzte Wartung", "choice", affects="note",
                     options=[("unter_2j", "Vor unter 2 Jahren"),
                              ("ueber_2j", "Vor über 2 Jahren / unbekannt")],
                     note_if={"ueber_2j": "wartungsstau"})],
      operations=[Op("wartung", "Wartung, Reinigung, Abgasmessung", "Stk", (1.2, 2.0)),
                  Op("material", "Dichtungen und Verschleißteile", "Stk", (0.0, 0.0),
                     kind="material", material_per_unit=(25, 65))]),

    J(key="sanitaer.dichtheitspruefung", messy=False, trade="sanitaer", group=G, segment=S,
      label_de="Dichtheitsprüfung mit Protokoll", unit="Stk",
      setup_hours=(0.3, 0.6), typical_size=(1, 1),
      market_band_at=(180, 420), market_band_de=(190, 450), band_basis="total",
      confidence="low", sources=SRC, note_keys=["protokoll_versicherung"],
      guided_form=[Q("umfang", "Umfang", "choice", affects="variant",
                     options=[("wohnung", "Wohnung"), ("haus", "Ganzes Haus")],
                     default="wohnung")],
      operations=[Op("pruefung", "Druckprobe durchführen", "Stk", (1.2, 2.5)),
                  Op("protokoll", "Protokoll erstellen", "Stk", (0.3, 0.7))]),

    # ── Komplettsanierung ─────────────────────────────────────────────
    J(key="sanitaer.bad_basis", trade="sanitaer", group=G, segment=S,
      label_de="Sanitärerneuerung (WC, Waschtisch, Dusche)", unit="Stk",
      setup_hours=(2.0, 4.0), typical_size=(1, 1),
      market_band_at=(3500, 7000), market_band_de=(3700, 7500), band_basis="total",
      confidence="high", sources=SRC,
      note_keys=["fliesen_nicht_enthalten", "abdichtung_nassbereich"],
      guided_form=[Q_BEWOHNT, Q_ZUGANG, Q_BAUJAHR,
                   Q("groesse", "Badgröße", "number", unit="m2", default=6,
                     affects="variant"),
                   Q("leitungen", "Leitungen erneuern?", "bool", affects="variant",
                     default=False, note_if={True: "steigleitung_zusatz"})],
      operations=[Op("demontage", "Altbestand demontieren", "Stk", (6, 11),
                     debris_kg_per_unit=(280, 600)),
                  Op("rohinstallation", "Rohinstallation Wasser/Abwasser", "Stk", (10, 18),
                     material_per_unit=(280, 620)),
                  Op("objekte", "Sanitärobjekte und Armaturen", "Stk", (0.0, 0.0),
                     kind="material", material_per_unit=(900, 2200)),
                  Op("montage", "Montage und Anschluss", "Stk", (8, 14)),
                  Op("abnahme", "Dichtheitsprüfung und Übergabe", "Stk", (1.0, 2.0))]),

    J(key="sanitaer.bad_komplett", trade="sanitaer", group=G, segment=S,
      label_de="Badsanierung komplett (inkl. Fliesen und Heizkörper)", unit="Stk",
      setup_hours=(3.0, 5.0), typical_size=(1, 1),
      market_band_at=(9000, 16000), market_band_de=(9500, 17000), band_basis="total",
      confidence="high", sources=SRC,
      note_keys=["abdichtung_nassbereich", "asbest_vor_1990", "koordination_gewerke",
                 "bad_nicht_nutzbar"],
      guided_form=[Q_BEWOHNT, Q_ZUGANG, Q_BAUJAHR,
                   Q("groesse", "Badgröße", "number", unit="m2", default=7,
                     affects="qty"),
                   Q("fliesen_alt", "Aufbau der alten Fliesen", "choice",
                     affects="variant",
                     options=[("duennbett", "Dünnbett"), ("dickbett", "Dickbett"),
                              ("unbekannt", "Unbekannt")],
                     default="unbekannt",
                     note_if={"unbekannt": "dickbett_mehraufwand"}),
                   Q("zweitbad", "Zweites Bad/WC vorhanden?", "bool", affects="note",
                     default=False, note_if={False: "bad_nicht_nutzbar"})],
      operations=[Op("demontage", "Komplettdemontage inkl. Fliesen", "Stk", (14, 26),
                     debris_kg_per_unit=(900, 2100)),
                  Op("rohinstallation", "Rohinstallation und Elektro", "Stk", (14, 24),
                     material_per_unit=(420, 900)),
                  Op("abdichtung", "Verbundabdichtung", "Stk", (3, 6),
                     material_per_unit=(120, 280)),
                  Op("fliesen", "Fliesenarbeiten", "Stk", (18, 32),
                     material_per_unit=(700, 1600)),
                  Op("objekte", "Sanitärobjekte, Armaturen, Heizkörper", "Stk", (0.0, 0.0),
                     kind="material", material_per_unit=(1400, 3200)),
                  Op("montage", "Endmontage und Übergabe", "Stk", (10, 18))]),
]
