from schema import JobType as J, Operation as Op

# ══ Bauen & Renovieren (1,224 businesses — largest building group) ════
BAUEN = [
    J(key="maurer.durchbruch", trade="maurer", group="Bauen & Renovieren",
      segment="Maurer & Betonbau", label_de="Wanddurchbruch mit Sturz", unit="Stk",
      setup_hours=(1.5, 2.5), typical_size=(1, 1),
      market_band_at=(900, 2600), market_band_de=(950, 2800), band_basis="total",
      confidence="medium", note_keys=["statik_pflicht", "staub", "abtransport"],
      operations=[
          Op("statik", "Abstützung stellen", "Stk", (1.5, 3.0)),
          Op("durchbruch", "Durchbruch herstellen", "Stk", (4.0, 8.0),
             debris_kg_per_unit=(350, 900)),
          Op("sturz", "Sturz einbauen", "Stk", (2.0, 4.0),
             material_per_unit=(180, 420)),
          Op("laibung", "Laibungen verputzen", "Stk", (2.0, 4.0),
             material_per_unit=(40, 90)),
      ]),
    J(key="maurer.wand_mauern", trade="maurer", group="Bauen & Renovieren",
      segment="Maurer & Betonbau", label_de="Wand mauern (nichttragend)", unit="m2",
      setup_hours=(1.0, 2.0), typical_size=(6, 25),
      market_band_at=(55, 110), market_band_de=(55, 115), confidence="medium",
      note_keys=["statik_nicht_tragend"],
      operations=[
          Op("mauern", "Mauerwerk herstellen", "m2", (0.40, 0.68),
             material_per_unit=(18, 32)),
          Op("verputzen", "Verputzen beidseitig", "m2", (0.24, 0.42),
             material_per_unit=(6, 12)),
      ]),
    J(key="metallbau.gelaender", trade="metallbau", group="Bauen & Renovieren",
      segment="Metallbau", label_de="Geländer fertigen und montieren", unit="lfm",
      setup_hours=(1.5, 3.0), typical_size=(3, 15),
      market_band_at=(180, 480), market_band_de=(190, 520), confidence="low",
      note_keys=["aufmass_vor_fertigung", "absturzsicherung_norm"],
      operations=[
          Op("aufmass", "Aufmaß vor Ort", "lfm", (0.10, 0.20)),
          Op("fertigung", "Fertigung in der Werkstatt", "lfm", (1.2, 2.4),
             material_per_unit=(70, 160)),
          Op("montage", "Montage und Verankerung", "lfm", (0.6, 1.2)),
      ]),
    J(key="geruest.standard", trade="geruest", group="Bauen & Renovieren",
      segment="Gerüstbau", label_de="Fassadengerüst (Auf-/Abbau + 4 Wochen)",
      unit="m2", setup_hours=(1.5, 3.0), typical_size=(80, 300),
      market_band_at=(6, 14), market_band_de=(6, 15), confidence="medium",
      note_keys=["standzeit", "genehmigung_strasse"],
      operations=[
          Op("aufbau", "Gerüst aufbauen", "m2", (0.05, 0.09)),
          Op("miete", "Gerüstmiete 4 Wochen", "m2", (0.0, 0.0), kind="material",
             material_per_unit=(2.20, 4.50)),
          Op("abbau", "Gerüst abbauen", "m2", (0.03, 0.06)),
      ]),
    J(key="schluessel.tueroeffnung", messy=False, trade="montage", group="Bauen & Renovieren",
      segment="Schlüsseldienst", label_de="Türöffnung (zugefallen)", unit="Stk",
      setup_hours=(0.8, 1.4), typical_size=(1, 1),
      market_band_at=(90, 250), market_band_de=(95, 280), band_basis="total",
      confidence="medium", note_keys=["identitaetsnachweis", "nacht_zuschlag"],
      operations=[
          Op("oeffnung", "Tür zerstörungsfrei öffnen", "Stk", (0.4, 1.0)),
          Op("anfahrt", "Anfahrt", "Stk", (0.3, 0.7), kind="travel"),
      ]),
    J(key="steinmetz.fensterbank", trade="maurer", group="Bauen & Renovieren",
      segment="Steinmetz", label_de="Fensterbank Naturstein tauschen", unit="Stk",
      setup_hours=(0.8, 1.5), typical_size=(1, 6),
      market_band_at=(180, 450), market_band_de=(190, 480), band_basis="total",
      confidence="low", note_keys=["aufmass_vor_fertigung"],
      operations=[
          Op("demontage", "Alte Bank entfernen", "Stk", (0.5, 1.0),
             debris_kg_per_unit=(25, 60)),
          Op("platte", "Steinplatte nach Maß", "Stk", (0.0, 0.0), kind="material",
             material_per_unit=(90, 240)),
          Op("montage", "Versetzen und verfugen", "Stk", (1.0, 2.0)),
      ]),
]

# ══ Möbel & Einrichtung — Tischler (839) ══════════════════════════════
TISCHLER = [
    J(key="tischler.innentuer", trade="tischler", group="Möbel & Einrichtung",
      segment="Tischler & Schreiner", label_de="Innentür inkl. Zarge tauschen",
      unit="Stk", setup_hours=(0.6, 1.2), typical_size=(1, 5),
      market_band_at=(380, 850), market_band_de=(400, 900), band_basis="total",
      confidence="medium", note_keys=["aufmass_vor_fertigung", "altgeraet_entsorgung"],
      operations=[
          Op("demontage", "Alte Tür und Zarge ausbauen", "Stk", (0.8, 1.5),
             debris_kg_per_unit=(30, 55)),
          Op("tuerblatt", "Türblatt und Zarge", "Stk", (0.0, 0.0), kind="material",
             material_per_unit=(180, 420)),
          Op("montage", "Zarge setzen, Tür einhängen, justieren", "Stk", (2.0, 3.5)),
          Op("anschluss", "Anschlussfugen schließen", "Stk", (0.4, 0.8),
             material_per_unit=(8, 18)),
      ]),
    J(key="tischler.einbauschrank", trade="tischler", group="Möbel & Einrichtung",
      segment="Tischler & Schreiner", label_de="Einbauschrank nach Maß", unit="lfm",
      setup_hours=(1.5, 3.0), typical_size=(2, 6),
      market_band_at=(650, 1600), market_band_de=(700, 1700), confidence="low",
      note_keys=["aufmass_vor_fertigung", "untergrund_eben"],
      operations=[
          Op("aufmass", "Aufmaß und Planung", "lfm", (0.4, 0.9)),
          Op("korpus", "Korpus und Fronten", "lfm", (0.0, 0.0), kind="material",
             material_per_unit=(320, 800), waste_factor=0.06),
          Op("fertigung", "Fertigung", "lfm", (2.5, 5.0)),
          Op("montage", "Montage vor Ort", "lfm", (1.5, 3.0)),
      ]),
    J(key="tischler.moebelmontage", messy=False, trade="tischler", group="Möbel & Einrichtung",
      segment="Tischler & Schreiner", label_de="Möbelmontage (Kaufmöbel)", unit="h",
      setup_hours=(0.5, 1.0), typical_size=(2, 8),
      market_band_at=(50, 85), market_band_de=(50, 90), confidence="medium",
      note_keys=["montageanleitung_bauseits"],
      operations=[Op("montage", "Möbel montieren", "h", (1.0, 1.0))]),
]

# ══ Küche (139) ═══════════════════════════════════════════════════════
KUECHE = [
    J(key="kueche.montage", trade="kueche", group="Küche", segment="Küchenbau",
      label_de="Küchenmontage (Standardküche)", unit="lfm",
      setup_hours=(1.5, 3.0), typical_size=(3, 8),
      market_band_at=(190, 420), market_band_de=(200, 450), confidence="medium",
      note_keys=["anschluesse_vorhanden", "wand_lot"],
      operations=[
          Op("unterschraenke", "Unterschränke stellen und ausrichten", "lfm", (0.75, 1.30)),
          Op("oberschraenke", "Oberschränke montieren", "lfm", (0.55, 1.00)),
          Op("arbeitsplatte", "Arbeitsplatte zuschneiden und montieren", "lfm", (0.65, 1.20),
             material_per_unit=(60, 160), waste_factor=0.08),
          Op("anschluss", "Geräte anschließen (E/Wasser)", "lfm", (0.30, 0.70)),
      ]),
    J(key="kueche.demontage", trade="kueche", group="Küche", segment="Küchenbau",
      label_de="Alte Küche demontieren und entsorgen", unit="lfm",
      setup_hours=(0.8, 1.5), typical_size=(3, 8),
      market_band_at=(55, 130), market_band_de=(58, 140), confidence="low",
      note_keys=["abtransport", "altgeraet_entsorgung"],
      operations=[
          Op("demontage", "Küche demontieren", "lfm", (0.6, 1.1),
             debris_kg_per_unit=(55, 110), debris_type="sperrmuell"),
          Op("entsorgung", "Entsorgung", "lfm", (0.0, 0.0), kind="disposal"),
      ]),
]
