from schema import JobType as J, Operation as Op

# ══ Garten & Außenbereich (454) ═══════════════════════════════════════
GARTEN = [
    J(key="garten.rasen_neu", trade="garten", group="Garten & Außenbereich",
      segment="Garten- & Landschaftsbau", label_de="Rasen neu anlegen (Saat)",
      unit="m2", setup_hours=(1.5, 3.0), typical_size=(80, 400),
      market_band_at=(8, 20), market_band_de=(8, 22), confidence="medium",
      note_keys=["bewaesserung_bauseits", "witterung"],
      operations=[
          Op("fraesen", "Boden fräsen und planieren", "m2", (0.020, 0.040)),
          Op("substrat", "Rasentragschicht", "m2", (0.010, 0.025),
             material_per_unit=(2.20, 4.50)),
          Op("saat", "Saat ausbringen und walzen", "m2", (0.008, 0.018),
             material_per_unit=(0.60, 1.40)),
      ]),
    J(key="garten.rollrasen", trade="garten", group="Garten & Außenbereich",
      segment="Garten- & Landschaftsbau", label_de="Rollrasen verlegen", unit="m2",
      setup_hours=(1.5, 3.0), typical_size=(60, 300),
      market_band_at=(14, 30), market_band_de=(15, 32), confidence="medium",
      note_keys=["bewaesserung_bauseits"],
      operations=[
          Op("vorbereitung", "Boden vorbereiten", "m2", (0.025, 0.045),
             material_per_unit=(2.00, 4.00)),
          Op("verlegen", "Rollrasen verlegen", "m2", (0.030, 0.055),
             material_per_unit=(6.00, 11.00), waste_factor=0.05),
      ]),
    J(key="garten.pflaster", trade="garten", group="Garten & Außenbereich",
      segment="Pflaster- & Straßenbau", label_de="Pflasterung (Betonstein)", unit="m2",
      setup_hours=(2.0, 4.0), typical_size=(25, 150),
      market_band_at=(60, 130), market_band_de=(60, 140), confidence="medium",
      note_keys=["unterbau_tragfaehig", "entwaesserung", "abtransport"],
      operations=[
          Op("aushub", "Aushub und Abtransport (Minibagger)", "m2", (0.09, 0.17),
             debris_kg_per_unit=(500, 750), debris_type="aushub"),
          Op("unterbau", "Frostschutz und Tragschicht", "m2", (0.11, 0.20),
             material_per_unit=(12, 22)),
          Op("bettung", "Splittbettung", "m2", (0.05, 0.11),
             material_per_unit=(3, 6)),
          Op("pflastern", "Pflaster verlegen und rütteln", "m2", (0.28, 0.52),
             material_per_unit=(18, 38), waste_factor=0.05),
      ]),
    J(key="garten.hecke_schnitt", messy=False, trade="garten", group="Garten & Außenbereich",
      segment="Garten- & Landschaftsbau", label_de="Hecke schneiden", unit="lfm",
      setup_hours=(0.5, 1.0), typical_size=(15, 80),
      market_band_at=(4, 12), market_band_de=(4, 13), confidence="medium",
      note_keys=["vogelschutz_zeitraum", "abtransport"],
      operations=[
          Op("schnitt", "Hecke schneiden", "lfm", (0.05, 0.11)),
          Op("gruenschnitt", "Grünschnitt entsorgen", "lfm", (0.02, 0.05),
             debris_kg_per_unit=(3, 9), debris_type="gruenschnitt"),
      ]),
    J(key="garten.zaun", trade="garten", group="Garten & Außenbereich",
      segment="Garten- & Landschaftsbau", label_de="Zaun setzen (Doppelstabmatte)",
      unit="lfm", setup_hours=(1.5, 2.5), typical_size=(20, 100),
      market_band_at=(45, 100), market_band_de=(48, 105), confidence="medium",
      note_keys=["grenzabstand", "leitungen_im_boden"],
      operations=[
          Op("fundamente", "Pfosten setzen und betonieren", "lfm", (0.30, 0.55),
             material_per_unit=(8, 16)),
          Op("matten", "Matten montieren", "lfm", (0.20, 0.40),
             material_per_unit=(22, 45)),
      ]),
    J(key="garten.pool", trade="garten", group="Garten & Außenbereich",
      segment="Poolbau", label_de="Pool einbauen (GFK-Becken, Standard)", unit="Stk",
      setup_hours=(4.0, 8.0), typical_size=(1, 1),
      market_band_at=(18000, 45000), market_band_de=(19000, 48000),
      band_basis="total", confidence="low",
      note_keys=["pool_untergrund", "genehmigung_bau", "leitungen_im_boden"],
      operations=[
          Op("aushub", "Aushub und Abtransport", "Stk", (14, 26),
             debris_kg_per_unit=(40000, 70000)),
          Op("becken", "Becken inkl. Technik", "Stk", (0.0, 0.0), kind="material",
             material_per_unit=(11000, 26000)),
          Op("einbau", "Einbau, Verrohrung, Technikraum", "Stk", (45, 90)),
          Op("umgebung", "Randgestaltung", "Stk", (12, 26),
             material_per_unit=(1200, 3500)),
      ]),
]

# ══ Fenster & Türen (287) ═════════════════════════════════════════════
FENSTER = [
    J(key="fenster.tausch", trade="fenster", group="Fenster & Türen",
      segment="Türen- & Fensterbau", label_de="Fenster tauschen (Kunststoff, 2-flg)",
      unit="Stk", setup_hours=(1.0, 2.0), typical_size=(1, 8),
      market_band_at=(650, 1500), market_band_de=(680, 1600), band_basis="total",
      confidence="medium", note_keys=["aufmass_vor_fertigung", "laibung_nacharbeit",
                                      "altgeraet_entsorgung"],
      operations=[
          Op("ausbau", "Altfenster ausbauen", "Stk", (1.0, 1.8),
             debris_kg_per_unit=(35, 70)),
          Op("element", "Fensterelement", "Stk", (0.0, 0.0), kind="material",
             material_per_unit=(380, 800)),
          Op("einbau", "Einbau, Befestigung, Abdichtung (RAL)", "Stk", (2.5, 4.5),
             material_per_unit=(35, 80)),
          Op("laibung", "Laibungen nacharbeiten", "Stk", (1.0, 2.0),
             material_per_unit=(15, 40), tier_min="standard"),
      ]),
    J(key="fenster.rolladen", trade="fenster", group="Fenster & Türen",
      segment="Rolladenbau", label_de="Rollladen nachrüsten (Aufsatz, elektrisch)",
      unit="Stk", setup_hours=(0.8, 1.5), typical_size=(1, 6),
      market_band_at=(420, 950), market_band_de=(450, 1000), band_basis="total",
      confidence="low", note_keys=["stromanschluss_bauseits"],
      operations=[
          Op("element", "Rollladenkasten und Panzer", "Stk", (0.0, 0.0),
             kind="material", material_per_unit=(230, 520)),
          Op("montage", "Montage", "Stk", (2.0, 3.5)),
          Op("elektro", "Motor anschließen", "Stk", (0.6, 1.2)),
      ]),
    J(key="fenster.markise", trade="fenster", group="Fenster & Türen",
      segment="Sonnenschutz & Markisen", label_de="Gelenkarmmarkise montieren",
      unit="Stk", setup_hours=(1.0, 1.8), typical_size=(1, 2),
      market_band_at=(1400, 3800), market_band_de=(1500, 4000), band_basis="total",
      confidence="low", note_keys=["untergrund_tragfaehig", "windklasse"],
      operations=[
          Op("markise", "Markise inkl. Motor", "Stk", (0.0, 0.0), kind="material",
             material_per_unit=(900, 2600)),
          Op("montage", "Konsolen setzen und montieren", "Stk", (3.0, 5.5)),
          Op("elektro", "Elektroanschluss", "Stk", (0.6, 1.2)),
      ]),
    J(key="glaser.scheibe", trade="fenster", group="Fenster & Türen",
      segment="Glaser", label_de="Isolierglasscheibe tauschen", unit="Stk",
      setup_hours=(0.6, 1.2), typical_size=(1, 4),
      market_band_at=(260, 700), market_band_de=(270, 750), band_basis="total",
      confidence="medium", note_keys=["aufmass_vor_fertigung"],
      operations=[
          Op("ausbau", "Altglas ausbauen", "Stk", (0.5, 1.0),
             debris_kg_per_unit=(18, 40)),
          Op("scheibe", "Isolierglas nach Maß", "Stk", (0.0, 0.0), kind="material",
             material_per_unit=(120, 340)),
          Op("einbau", "Verglasen und verklotzen", "Stk", (0.8, 1.6)),
      ]),
]

# ══ Dacharbeiten (285) ════════════════════════════════════════════════
DACH = [
    J(key="dach.ziegel_umdecken", trade="dach", group="Dacharbeiten",
      segment="Dachdecker", label_de="Dach umdecken (Ziegel, inkl. Lattung)",
      unit="m2", setup_hours=(3.0, 6.0), typical_size=(80, 250),
      market_band_at=(75, 160), market_band_de=(80, 170), confidence="medium",
      note_keys=["geruest_erforderlich", "witterung", "asbest_vor_1990",
                 "abtransport"],
      operations=[
          Op("abdecken", "Altdeckung abnehmen", "m2", (0.10, 0.20),
             debris_kg_per_unit=(40, 70)),
          Op("lattung", "Konterlattung und Lattung", "m2", (0.12, 0.22),
             material_per_unit=(6, 12)),
          Op("unterspann", "Unterspannbahn", "m2", (0.05, 0.10),
             material_per_unit=(2.50, 5.00)),
          Op("eindecken", "Neu eindecken", "m2", (0.28, 0.50),
             material_per_unit=(22, 45), waste_factor=0.06),
      ]),
    J(key="dach.rinne", trade="dach", group="Dacharbeiten",
      segment="Spengler / Klempner", label_de="Dachrinne erneuern", unit="lfm",
      setup_hours=(1.5, 3.0), typical_size=(10, 40),
      market_band_at=(45, 110), market_band_de=(48, 115), confidence="medium",
      note_keys=["geruest_erforderlich", "witterung"],
      operations=[
          Op("demontage", "Altrinne demontieren", "lfm", (0.10, 0.20),
             debris_kg_per_unit=(2, 5)),
          Op("rinne", "Rinne und Fallrohr", "lfm", (0.0, 0.0), kind="material",
             material_per_unit=(18, 42)),
          Op("montage", "Rinneisen setzen und montieren", "lfm", (0.35, 0.65)),
      ]),
    J(key="dach.flachdach", trade="dach", group="Dacharbeiten",
      segment="Dachdecker", label_de="Flachdach abdichten (Bitumen 2-lagig)",
      unit="m2", setup_hours=(2.5, 5.0), typical_size=(50, 200),
      market_band_at=(60, 130), market_band_de=(62, 135), confidence="low",
      note_keys=["gefaelle", "witterung", "abtransport"],
      operations=[
          Op("untergrund", "Untergrund vorbereiten", "m2", (0.08, 0.16)),
          Op("daemmung", "Dämmung verlegen", "m2", (0.10, 0.18),
             material_per_unit=(18, 34)),
          Op("abdichtung", "Zweilagige Abdichtung", "m2", (0.25, 0.45),
             material_per_unit=(14, 28), waste_factor=0.08),
      ]),
    J(key="dach.kaminkehren", messy=False, trade="dach", group="Dacharbeiten",
      segment="Schornsteinfeger", label_de="Kaminkehrung und Messung", unit="Stk",
      setup_hours=(0.2, 0.4), typical_size=(1, 1),
      market_band_at=(45, 120), market_band_de=(50, 130), band_basis="total",
      confidence="medium", note_keys=["behoerdlich_vorgeschrieben"],
      operations=[Op("kehrung", "Kehrung und Abgasmessung", "Stk", (0.4, 0.9))]),
]
